#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TeamToDo.Android.Resource", IsApplication=true)]

namespace TeamToDo.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FHXamarinAndroidSDK.Resource.String.library_name = global::TeamToDo.Android.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_new = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06001a
			public const int action_add = 2131099674;
			
			// aapt resource value: 0x7f06000a
			public const int assignToView = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int createTaskButton = 2131099660;
			
			// aapt resource value: 0x7f060019
			public const int deadlineField = 2131099673;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout1 = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout2 = 2131099653;
			
			// aapt resource value: 0x7f060017
			public const int linearLayout3 = 2131099671;
			
			// aapt resource value: 0x7f06000d
			public const int linearLayout4 = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int linearLayout5 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int linearLayout6 = 2131099664;
			
			// aapt resource value: 0x7f060009
			public const int linearLayout7 = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int loginButton = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int passwordField = 2131099655;
			
			// aapt resource value: 0x7f060012
			public const int saveTaskDetailsButton = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int taskCompletedField = 2131099665;
			
			// aapt resource value: 0x7f060016
			public const int taskDescField = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int taskDetails = 2131099668;
			
			// aapt resource value: 0x7f06000e
			public const int taskNoteField = 2131099662;
			
			// aapt resource value: 0x7f060013
			public const int taskTitle = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int taskTitleField = 2131099669;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int textView2 = 2131099651;
			
			// aapt resource value: 0x7f060018
			public const int textView3 = 2131099672;
			
			// aapt resource value: 0x7f060006
			public const int textView4 = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int textView5 = 2131099649;
			
			// aapt resource value: 0x7f06000b
			public const int userSelector = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int usernameField = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int TaskCreate = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int TaskDetails = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int TasklistItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int tasks_shared_fields = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int list_actions = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int action_new = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int exit_app = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
